In [40]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


from sklearn.model_selection import train_test_split
from sklearn.impute import KNNImputer,SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [41]:
df=pd.read_csv('train.csv')[['Age','Pclass','Fare','Survived']]

In [42]:
df.head()

    Age  Pclass     Fare  Survived
0  22.0       3   7.2500         0
1  38.0       1  71.2833         1
2  26.0       3   7.9250         1
3  35.0       1  53.1000         1
4  35.0       3   8.0500         0

In [43]:
X_train,X_test,Y_train,Y_test=train_test_split(df.drop(columns=['Survived']),
                                              df['Survived'],
                                              test_size=0.2,
                                              random_state=42)

In [44]:
X_train

      Age  Pclass      Fare
331  45.5       1   28.5000
733  23.0       2   13.0000
382  32.0       3    7.9250
704  26.0       3    7.8542
813   6.0       3   31.2750
..    ...     ...       ...
106  21.0       3    7.6500
270   NaN       1   31.0000
860  41.0       3   14.1083
435  14.0       1  120.0000
102  21.0       1   77.2875

[712 rows x 3 columns]

In [45]:
df.isnull().mean()*100

Age         19.86532
Pclass       0.00000
Fare         0.00000
Survived     0.00000
dtype: float64

In [46]:
knn=KNNImputer(n_neighbors=3,weights='distance')

X_train_trf=knn.fit_transform(X_train)
X_test_trf=knn.transform(X_test)

In [47]:
pd.DataFrame(X_train_trf,columns=X_train.columns)

      Age  Pclass      Fare
0    45.5     1.0   28.5000
1    23.0     2.0   13.0000
2    32.0     3.0    7.9250
3    26.0     3.0    7.8542
4     6.0     3.0   31.2750
..    ...     ...       ...
707  21.0     3.0    7.6500
708  37.0     1.0   31.0000
709  41.0     3.0   14.1083
710  14.0     1.0  120.0000
711  21.0     1.0   77.2875

[712 rows x 3 columns]

In [48]:
lr=LogisticRegression()
lr.fit(X_train_trf,Y_train)
y_pred=lr.predict(X_test_trf)
accuracy_score(Y_test,y_pred)

0.7374301675977654